[package]
name = "nrg-mesh-to-volume-conversion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
easy-gltf = "1.1.2"
nalgebra = "0.32.5"
glam = "0.27.0"
